using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;

namespace Eathere.Models
{
    public class DishType
    {
        [Key] // ID WILL BE PK 
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)] //id will be auto generated BY DB
        public Guid Id { get; set; }
        public string TypeName { get; set; } //main,soup,dessert,drink,snack,addition
        public bool IsVegan { get; set; }
        public bool HasAlcohol { get; set; }
        
    }
}
