using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;

namespace Eathere.Models
{
    public class PortionType
    {
        [Key] // ID WILL BE PK 
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)] //id will be auto generated BY DB
        public Guid Id { get; set; }
        public string Name { get; set; }// grams/mls/piece
        public Guid RestaurantId { get; set; }
        [ForeignKey("RestaurantId")]
        public virtual Restaurant? Restaurant { get; set; }
    }
}
