using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Eathere.Models
{
    public class User
    {
        [Key] // ID WILL BE PK 
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)] //id will be auto generated BY DB
        public Guid Id { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Gender { get; set; } 
        public string Email { get; set; }
        public string Password { get; set; }
        public Guid RestaurantId { get; set; }
        public string RestaurantRole { get; set; }
        public DateTime BirthdatDate { get; set; }

        [DatabaseGenerated(DatabaseGeneratedOption.Computed)]// date will be auto generated by id
        public DateTime? RegisterDate { get; set; }
    }
}